sudo: false
language: python

install:
  - pip install --upgrade pip setuptools
  - pip install -r dev-requirements.txt

jobs:
  include:
    - script: python -m pytest tests.py
      python: "3.7"
      name: "Python 3.7"

    - script: python -m pytest tests.py
      python: "3.6"
      name: "Python 3.6"

    - script: pre-commit run --all-files --show-diff-on-failure
      python: "3.6"
      name: "Linting"
